version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/new_frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/BACKEND"
    schedule:
      interval: "weekly"
