version: '3.8'

services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - userdb:/var/lib/postgresql/data

volumes:
  userdb:
